AWSTemplateFormatVersion: '2010-09-09'
Description: SicarioSpec CloudFormation starter

Parameters:
  Environment:
    Type: String
    Description: Deployment environment

Resources: {}

Outputs:
  SicarioIacProfile:
    Value: cloud-iac

