apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sicario-require-non-root
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must run as non-root unless an approved exception exists."
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
